apiVersion: app/v1
kind: Deployment
metada:
  name: my-deployment-first
spec:
  replicas: 3
  selector:
    matchLabels: 
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
         image: nginx
         name: my-deployment-first
         ports: 
           - containerPort: 80


# targetPort: 3000 # Forward traffic to Pod’s container port